package com.aes.model;
// Generated Nov 9, 2015 6:58:38 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * ExamScores generated by hbm2java
 */
@Entity
@Table(name="exam_scores"
    ,catalog="aes"
)
public class ExamScores  implements java.io.Serializable {


     private Integer id;
     private Exam exam;
     private User user;
     private float score;
     private float maxScore;
     private Date dateTaken;
     private int timesTaken;
     private int passingPercentage;

    public ExamScores() {
    }

    public ExamScores(Exam exam, User user, float score, Date dateTaken, int timesTaken) {
       this.exam = exam;
       this.user = user;
       this.score = score;
       this.dateTaken = dateTaken;
       this.timesTaken = timesTaken;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="exam", nullable=false)
    @JsonManagedReference
    public Exam getExam() {
        return this.exam;
    }
    
    public void setExam(Exam exam) {
        this.exam = exam;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user", nullable=false)
    @JsonManagedReference
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="score", nullable=false, precision=12, scale=0)
    public float getScore() {
        return this.score;
    }
    
    public void setScore(float score) {
        this.score = score;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_taken", nullable=false, length=19)
    public Date getDateTaken() {
        return this.dateTaken;
    }
    
    public void setDateTaken(Date dateTaken) {
        this.dateTaken = dateTaken;
    }

    
    @Column(name="times_taken", nullable=false)
    public int getTimesTaken() {
        return this.timesTaken;
    }
    
    public void setTimesTaken(int timesTaken) {
        this.timesTaken = timesTaken;
    }

    @Column(name="max_score", nullable=false, precision=12, scale=0)
    public float getMaxScore() {
        return this.maxScore;
    }
    
    public void setMaxScore(float maxScore) {
        this.maxScore = maxScore;
    }

    @Column(name="passing_percentage", nullable=false)
    public int getPassingPercentage() {
        return this.passingPercentage;
    }
    
    public void setPassingPercentage(int passingPercentage) {
        this.passingPercentage = passingPercentage;
    }


}


